# Generated by Django 5.2.3 on 2025-06-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at the time of adding to cart', max_digits=10, null=True),
        ),
    ]
