# Generated by Django 5.2.3 on 2025-06-22 14:25

from django.db import migrations


def backfill_cart_item_prices(apps, schema_editor):
    """
    Backfill price field in CartItem with current product prices
    """
    CartItem = apps.get_model('store', 'CartItem')
    
    # Update all cart items that don't have a price set
    for cart_item in CartItem.objects.filter(price__isnull=True):
        cart_item.price = cart_item.product.price
        cart_item.save()


def reverse_backfill_cart_item_prices(apps, schema_editor):
    """
    Reverse migration - set price field back to null
    """
    CartItem = apps.get_model('store', 'CartItem')
    CartItem.objects.update(price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_price'),
    ]

    operations = [
        migrations.RunPython(
            backfill_cart_item_prices,
            reverse_backfill_cart_item_prices,
        ),
    ]
