# Generated by Django 5.2.3 on 2025-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20250622_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price at the time of adding to cart', max_digits=10),
        ),
    ]
