# Generated by Django 5.2.3 on 2025-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod',
            field=models.BooleanField(default=False, help_text='Is this order Cash on Delivery?'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique Order ID (auto-generated)', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', help_text='Order status', max_length=32),
        ),
    ]
